#!/usr/bin/env python
import sqlite3
import socket
import time
import datetime as dt
import base64
import pickle

HOST = ''
PORT = 12999

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)

s.bind((HOST,PORT))
s.listen(10)

conn, addr = s.accept()
print('Conectado com', addr[0],':', str(addr[1]))

con = sqlite3.connect('edgedb')
c = con.cursor()

#c.execute('CREATE TABLE imagebank (id INTEGER PRIMARY KEY AUTOINCREMENT, picture BLOB)') #TABELA JÁ CRIADA
numba = 0

while True:
    
    data = conn.recv(4432).decode('utf-8')
    print('data recv = ', data)
    archive = base64.b64decode(data)
    print('archive type =', type(archive))
    print('archive = ', archive)
    with open("image_receivedtest2.png", "wb") as image_file:
        image_file.write(archive)
    #c.execute('INSERT INTO imagebank (picture) VALUES (?)' , [archive])
    con.commit()
    numba += 1

    if not data:
        break
    

s.close()
