#!/usr/bin/env python
import tkinter as tk
from tkinter import filedialog
import socket
import random
import time
import datetime as dt
import base64
import json

global arquivo
global s


HOST = socket.gethostname()
PORT = 12999
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
s.connect((HOST,PORT))


def openthat():
    global arquivo
    global photostr
    arquivo =  filedialog.askopenfilename(initialdir = "/home/telespazio", title = "Selecione o arquivo")
    print (arquivo)
    with open(arquivo, 'rb') as input_file:
        photostr = base64.b64encode(input_file.read())
        print(len(photostr))
        print('photostr =', photostr)
    return len(photostr)


def sendimg():
    global photostr    
    s.send(photostr)
    time.sleep(10)
    s.close()

root = tk.Tk()
root.title('Janela do Cliente')
botao = tk.Button(root, text='Abrir Imagem', command = openthat)
botao.pack()
sendbtn = tk.Button(root, text='Enviar Imagem', command = sendimg)
sendbtn.pack()
closebtn = tk.Button(root, text='Fechar', command = root.destroy)
closebtn.pack()

root.mainloop()
