#!/usr/bin/env python
import time
import serial
import tkinter as tk
from tkinter import ttk
import threading

ser = serial.Serial(
              
    port='/dev/ttyUSB0',
    baudrate = 19200,
    parity=serial.PARITY_NONE,
    stopbits=serial.STOPBITS_ONE,
    bytesize=serial.EIGHTBITS,
    timeout=1
    )

class MyThread(threading.Thread):
    
    def __init__(self):    
        super(MyThread, self).__init__()
        
        
    def run(self):
        
        global i
        
        i = 0
        
        with lock:
            while True:
                if lock.locked() == True:
                    print('Lock state :', lock.locked())
                    x = ser.readline()
                    y = x.rstrip()
                    z = y.decode('utf-8')
                    print(z)
                    ser.write(str.encode('AT+CSQ\r'))
                    time.sleep(8)
                    if (z.startswith("+CSQ")):
                        a = int(z[5])
                        if a >= 3:
                            print('Qualidade do sinal', z[5], 'é suficiente')
                            lock.release()
                            i = i + 1
                            print('primeiro print i: ',i)
                            print("Lock state : ", lock.locked())
                            time.sleep(10)
                            if i >= 1:
                                i = i - 1
                                print('segundo print i: ',i)
                            
                        else:
                            print('Buscando Sinal...')
                            time.sleep(0.5)
                else:
                    lock.acquire()

                    
lock = threading.Lock()
                    
                    
thread = MyThread()
thread.start()
thread.join()
