#!/usr/bin/env python
import time
import serial
import tkinter as tk
from tkinter import ttk
import threading

ser = serial.Serial(
              
    port='/dev/ttyUSB0',
    baudrate = 19200,
    parity=serial.PARITY_NONE,
    stopbits=serial.STOPBITS_ONE,
    bytesize=serial.EIGHTBITS,
    timeout=1
    )

lock = threading.Lock()

class TestThreading(object):
    
    def __init__(self):
        thread = threading.Thread(target=self.run, args=())
        thread.daemon = True
        thread.start()

    def run(self):
        lock.acquire()
        while True:
            x = ser.readline()
            y = x.rstrip()
            z = y.decode('utf-8')
            print(z)
            ser.write(str.encode('AT+CSQ\r'))
            time.sleep(5)
            if (z.startswith("+CSQ")):
                a = int(z[5])
                if a >= 3:
                    print('Qualidade do sinal', z[5], 'é suficiente')
                    lock.release()
                    read_mt_message()
                else:
                    print('Buscando Sinal...')

tr = TestThreading()
time.sleep(1)
print(' : First output')

